name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: Add reviewers and labels
        uses: label-when-approved-action
        env:
          APPROVALS: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: ready%20to%20merge
          REMOVE_LABEL: pendind%20approval
